package com.bam.sshfs.crypto

import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.security.keystore.UserNotAuthenticatedException
import java.security.GeneralSecurityException
import java.security.KeyStore
import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Seals secrets — private keys and passwords — under an AES key that lives in the
 * Android Keystore and never leaves it. The database and preferences only ever hold
 * the blob this produces, so a dump of either yields nothing usable.
 *
 * Two schemes coexist, told apart by the blob's version prefix:
 *
 * - `v1:` — a plain Keystore key. Readable whenever the app runs.
 * - `v2:` — a *user-authentication-gated* key. Opening one needs a fingerprint or the
 *   device PIN within the last [AUTH_WINDOW_SECONDS] seconds.
 *
 * Both are `Base64(12-byte IV ‖ GCM ciphertext+tag)` after the prefix; a blob with
 * *no* prefix predates encryption and is read back as plain Base64 so existing rows
 * keep working, then re-sealed on the next write.
 *
 * Which scheme a *write* uses is decided per call by [gated] — the setting the user
 * toggles. Reads never consult it, so flipping the setting can't orphan a blob;
 * [SecretResealer] converts the existing ones in the background.
 */
class KeystoreSecretStore(
    private val alias: String = DEFAULT_ALIAS,
    private val gatedAlias: String = GATED_ALIAS,
    private val gated: () -> Boolean = { false },
) : SecretStore {

    override fun encrypt(plaintext: String): String {
        val useGate = gated()
        val prefix = if (useGate) PREFIX_V2 else PREFIX_V1
        val cipher = try {
            Cipher.getInstance(TRANSFORMATION)
                .apply { init(Cipher.ENCRYPT_MODE, secretKey(useGate)) }
        } catch (e: UserNotAuthenticatedException) {
            throw AuthenticationRequiredException(cause = e)
        } catch (e: GeneralSecurityException) {
            throw SecretStoreException("Could not open the Keystore key to seal a secret.", e)
        }
        val sealed = try {
            cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
        } catch (e: GeneralSecurityException) {
            throw SecretStoreException("Could not encrypt the secret.", e)
        }
        // The IV is generated by the Keystore, not by us — prepend it so decrypt can find it.
        val blob = cipher.iv + sealed
        return prefix + Base64.getEncoder().encodeToString(blob)
    }

    override fun decrypt(ciphertext: String): String {
        val useGate = when {
            ciphertext.startsWith(PREFIX_V2) -> true
            ciphertext.startsWith(PREFIX_V1) -> false
            else -> return legacy.decrypt(ciphertext)
        }
        val prefix = if (useGate) PREFIX_V2 else PREFIX_V1

        val blob = try {
            Base64.getDecoder().decode(ciphertext.removePrefix(prefix))
        } catch (e: IllegalArgumentException) {
            throw SecretStoreException("Stored secret is not valid Base64.", e)
        }
        if (blob.size <= IV_BYTES) throw SecretStoreException("Stored secret is truncated.")

        val iv = blob.copyOfRange(0, IV_BYTES)
        val sealed = blob.copyOfRange(IV_BYTES, blob.size)
        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, secretKey(useGate), GCMParameterSpec(TAG_BITS, iv))
            String(cipher.doFinal(sealed), Charsets.UTF_8)
        } catch (e: UserNotAuthenticatedException) {
            // Recoverable: the gated key is locked, not gone. Prompt and retry.
            throw AuthenticationRequiredException(cause = e)
        } catch (e: GeneralSecurityException) {
            // Also the path taken when the key was dropped — a device credential reset
            // wipes Keystore entries, and the old blobs become permanently unreadable.
            throw SecretStoreException("Stored secret could not be decrypted.", e)
        }
    }

    /** Fetch the plain or gated AES key, creating it on first use. */
    private fun secretKey(gated: Boolean): SecretKey {
        val name = if (gated) gatedAlias else alias
        val store = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (store.getEntry(name, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        generator.init(specFor(name, gated))
        return generator.generateKey()
    }

    /** The key parameters: identical but for the authentication gate on the v2 key. */
    private fun specFor(name: String, gated: Boolean): KeyGenParameterSpec =
        KeyGenParameterSpec.Builder(
            name,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            // GCM must never reuse an IV under one key; let the Keystore pick them.
            .setRandomizedEncryptionRequired(true)
            .apply {
                if (!gated) return@apply
                setUserAuthenticationRequired(true)
                // Time-bound rather than per-use: one prompt covers the connect, the
                // re-dials and the provider's reads for the whole window, and no
                // CryptoObject has to be threaded through the transport layer.
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                    setUserAuthenticationParameters(
                        AUTH_WINDOW_SECONDS,
                        KeyProperties.AUTH_BIOMETRIC_STRONG or
                            KeyProperties.AUTH_DEVICE_CREDENTIAL,
                    )
                } else {
                    @Suppress("DEPRECATION")
                    setUserAuthenticationValidityDurationSeconds(AUTH_WINDOW_SECONDS)
                }
            }
            .build()

    private val legacy = PassthroughSecretStore()

    companion object {
        const val DEFAULT_ALIAS = "com.bam.sshfs.secrets"
        const val GATED_ALIAS = "com.bam.sshfs.secrets.gated"
        private const val PROVIDER = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val PREFIX_V1 = "v1:"
        private const val PREFIX_V2 = "v2:"
        private const val IV_BYTES = 12
        private const val TAG_BITS = 128

        /**
         * How long one authentication keeps the gated key usable.
         *
         * Long enough that browsing a root in the file picker doesn't re-prompt
         * mid-listing, short enough that a handed-over unlocked phone doesn't leave
         * the keys readable for the rest of the day.
         */
        const val AUTH_WINDOW_SECONDS = 300

        /** True when any of [blobs] is gated and so needs an unlock before reading. */
        fun needsAuthentication(vararg blobs: String?): Boolean =
            blobs.any { it != null && it.startsWith(PREFIX_V2) }

        /** Drop the gated key, making every remaining `v2:` blob unreadable forever. */
        fun deleteGatedKey(gatedAlias: String = GATED_ALIAS) {
            runCatching {
                KeyStore.getInstance(PROVIDER).apply { load(null) }.deleteEntry(gatedAlias)
            }
        }
    }
}
