package com.bam.sshfs.crypto

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.GeneralSecurityException
import java.security.KeyStore
import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Seals secrets — private keys and passwords — under an AES key that lives in the
 * Android Keystore and never leaves it. The database and preferences only ever hold
 * the blob this produces, so a dump of either yields nothing usable.
 *
 * Blob format is `v1:` + Base64(12-byte IV ‖ GCM ciphertext+tag). The version prefix
 * is what lets a later scheme (a user-authentication-gated key, say) be told apart
 * from this one; a blob with *no* prefix predates encryption and is read back as
 * plain Base64 so existing rows keep working, then re-sealed on the next write.
 */
class KeystoreSecretStore(
    private val alias: String = DEFAULT_ALIAS,
) : SecretStore {

    override fun encrypt(plaintext: String): String {
        val cipher = try {
            Cipher.getInstance(TRANSFORMATION).apply { init(Cipher.ENCRYPT_MODE, secretKey()) }
        } catch (e: GeneralSecurityException) {
            throw SecretStoreException("Could not open the Keystore key to seal a secret.", e)
        }
        val sealed = try {
            cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
        } catch (e: GeneralSecurityException) {
            throw SecretStoreException("Could not encrypt the secret.", e)
        }
        // The IV is generated by the Keystore, not by us — prepend it so decrypt can find it.
        val blob = cipher.iv + sealed
        return PREFIX_V1 + Base64.getEncoder().encodeToString(blob)
    }

    override fun decrypt(ciphertext: String): String {
        if (!ciphertext.startsWith(PREFIX_V1)) return legacy.decrypt(ciphertext)

        val blob = try {
            Base64.getDecoder().decode(ciphertext.removePrefix(PREFIX_V1))
        } catch (e: IllegalArgumentException) {
            throw SecretStoreException("Stored secret is not valid Base64.", e)
        }
        if (blob.size <= IV_BYTES) throw SecretStoreException("Stored secret is truncated.")

        val iv = blob.copyOfRange(0, IV_BYTES)
        val sealed = blob.copyOfRange(IV_BYTES, blob.size)
        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(TAG_BITS, iv))
            String(cipher.doFinal(sealed), Charsets.UTF_8)
        } catch (e: GeneralSecurityException) {
            // Also the path taken when the key was dropped — a device credential reset
            // wipes Keystore entries, and the old blobs become permanently unreadable.
            throw SecretStoreException("Stored secret could not be decrypted.", e)
        }
    }

    /** Fetch the app's AES key, creating it on first use. */
    private fun secretKey(): SecretKey {
        val store = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (store.getEntry(alias, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        generator.init(
            KeyGenParameterSpec.Builder(
                alias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                // GCM must never reuse an IV under one key; let the Keystore pick them.
                .setRandomizedEncryptionRequired(true)
                .build()
        )
        return generator.generateKey()
    }

    private val legacy = PassthroughSecretStore()

    companion object {
        const val DEFAULT_ALIAS = "com.bam.sshfs.secrets"
        private const val PROVIDER = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val PREFIX_V1 = "v1:"
        private const val IV_BYTES = 12
        private const val TAG_BITS = 128
    }
}
